/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package mx.itson.benito.ui;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.ListModel;
import javax.swing.table.DefaultTableModel;
import mx.itson.benito.entidades.*;
import mx.itson.benito.persistencia.*;

/**
 *
 * @author shiri
 */
public class GuardarOrden extends javax.swing.JDialog {

    int idOrden;
    
    /**
     * Creates new form GuardarOrden
     */
    public GuardarOrden(java.awt.Frame parent, boolean modal, int id) {
        super(parent, modal);
        initComponents();
        
        DateFormat formato = new SimpleDateFormat("dd/MMMM/yyyy");
        
        idOrden = id;
        
        cboProveedores.removeAllItems();
        cboDias.removeAllItems();
        cboAnios.removeAllItems();
        
        CambiarDias();
        agregarProveedores();
        
        if(idOrden != 0){
            
            OrdenCompraDAO ord = new OrdenCompraDAO();
            OrdenCompra orden = ord.obtenerPorId(this.idOrden);
            
            txtCliente.setText(orden.getCliente());
            txtDireccion.setText(orden.getDireccion());
            txtTelefono.setText(orden.getTelefono());
            txtFolio.setText(orden.getFolio());
            
            
            Date fecha = orden.getFecha();
            String fech = formato.format(fecha);
            String f[] = fech.split("/");
            
            cboMeses.setSelectedItem(f[1]);
            cboDias.setSelectedItem(f[0]);
            cboAnios.setSelectedItem(f[2]);
            
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtCliente = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cboProveedores = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtFolio = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cboMeses = new javax.swing.JComboBox<>();
        cboDias = new javax.swing.JComboBox<>();
        cboAnios = new javax.swing.JComboBox<>();
        btnGuardar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblArticulos = new javax.swing.JTable();
        btnAgregarArticulo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Cliente");

        jLabel2.setText("Direccion");

        jLabel3.setText("Telefono");

        jLabel4.setText("Proveedor");

        cboProveedores.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboProveedoresItemStateChanged(evt);
            }
        });

        jLabel5.setText("Folio");

        jLabel7.setText("Fecha");

        cboMeses.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        cboMeses.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboMesesItemStateChanged(evt);
            }
        });
        cboMeses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboMesesActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        tblArticulos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Nombre"
            }
        ));
        jScrollPane2.setViewportView(tblArticulos);

        btnAgregarArticulo.setText("Agregar articulo");
        btnAgregarArticulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarArticuloActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtCliente)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtDireccion)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtTelefono)
                    .addComponent(cboProveedores, 0, 782, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtFolio)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cboMeses, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboDias, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboAnios, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnGuardar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAgregarArticulo)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFolio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboMeses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboDias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboAnios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAgregarArticulo)
                .addGap(12, 12, 12)
                .addComponent(btnGuardar))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboMesesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboMesesItemStateChanged

        cboDias.removeAllItems();
        cboAnios.removeAllItems();
        CambiarDias();
        
    }//GEN-LAST:event_cboMesesItemStateChanged

    private void cboMesesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboMesesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboMesesActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        
        try{
            
            SimpleDateFormat formato = new SimpleDateFormat("dd/MMMM/yyyy");

            String cliente = txtCliente.getText();
            String direccion = txtDireccion.getText();
            String telefono = txtTelefono.getText();
            Proveedor proveedor = (Proveedor)cboProveedores.getSelectedItem();
            String folio = txtFolio.getText();
            String fech = cboDias.getSelectedItem().toString() + "/" + cboMeses.getSelectedItem().toString() + "/" + cboAnios.getSelectedItem().toString();
            Date fecha = formato.parse(fech);
                        
            List<Articulo> articulos = new ArrayList<>();
            float subtotal = 0;
             
            boolean funco = this.idOrden == 0 ?
            new OrdenCompraDAO().guardar(cliente, direccion, telefono, proveedor, folio, subtotal, fecha, articulos):
            new OrdenCompraDAO().editar(idOrden, cliente, direccion, telefono, proveedor, folio, subtotal, fecha, articulos);

            if(funco){ 

                JOptionPane.showMessageDialog(this, "El registro fue exitoso", "Guardado", JOptionPane.INFORMATION_MESSAGE);

                dispose();

            }else{

                JOptionPane.showMessageDialog(this, "El registro tuvo un error", "No guardado", JOptionPane.ERROR_MESSAGE);

                dispose();

            }

        }catch(Exception ex){

            System.err.println("Ocurrio un error: " + ex.getMessage());

        }
        
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void cboProveedoresItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboProveedoresItemStateChanged
        
        cargarArticulos();
        
    }//GEN-LAST:event_cboProveedoresItemStateChanged

    private void btnAgregarArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarArticuloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarArticuloActionPerformed

    public void cargarArticulos(){
        
        ArticuloDAO ar = new ArticuloDAO();
        Proveedor pr;
        
        pr = (Proveedor)cboProveedores.getSelectedItem();
        DefaultTableModel modelo = (DefaultTableModel) tblArticulos.getModel();
        
        List<Articulo> articulos = ar.ObtenerTodos();
        
        for(Articulo a : articulos){
            
            if(a.getNombre().equals(pr)){
            } else {
                modelo.addRow(new Object[] {a.getNombre()});
            }

        }
        
    }
    
    /**
     * Sirve para agregar todos los proveedores existentes al combobox de proveedores
     */
    public void agregarProveedores(){
        
        ProveedorDAO pr = new ProveedorDAO();
        List<Proveedor> proveedores = pr.ObtenerTodos();
        
        try{
            
            for(Proveedor p : proveedores){
            
                cboProveedores.addItem(p);
            
            }
            
        }catch(Exception ex){
            
            System.err.println("Ocurrio un error: " + ex.getMessage());
            
        }
        
    }
    
    /**
     * Sirve para llenar los combo box de los dias y los años
     */
    public void CambiarDias(){
        
         try{
             
             int dia = 1;
             int i = 0;
             int a = 1900;
             
             while(a <= 2100){
                 
                 cboAnios.addItem(Integer.toString(a));
                 a++;
                 
             }
            
             if(cboMeses.getSelectedItem().toString().equals("January")){
                 
                 while(i < 31){
                     
                     cboDias.addItem(Integer.toString(dia));
                     i++;
                     dia++;
                     
                 }
                 
             }else if(cboMeses.getSelectedItem().toString().equals("February")){
                 
                 while(i < 29){
                     
                     cboDias.addItem(Integer.toString(dia));
                     i++;
                     dia++;
                     
                 }
                 
             }else if(cboMeses.getSelectedItem().toString().equals("March")){
                 
                 while(i < 31){
                     
                     cboDias.addItem(Integer.toString(dia));
                     i++;
                     dia++;
                     
                 }
                 
             }else if(cboMeses.getSelectedItem().toString().equals("April")){
                 
                 while(i < 30){
                     
                     cboDias.addItem(Integer.toString(dia));
                     i++;
                     dia++;
                     
                 }
                 
             }else if(cboMeses.getSelectedItem().toString().equals("May")){
                 
                 while(i < 31){
                     
                    cboDias.addItem(Integer.toString(dia));
                     i++;
                     dia++;
                     
                 }
                 
             }else if(cboMeses.getSelectedItem().toString().equals("June")){
                 
                 while(i < 30){
                     
                     cboDias.addItem(Integer.toString(dia));
                     i++;
                     dia++;
                     
                 }
                 
             }else if(cboMeses.getSelectedItem().toString().equals("July")){
                 
                 while(i < 31){
                     
                     cboDias.addItem(Integer.toString(dia));
                     i++;
                     dia++;
                     
                 }
                 
             }else if(cboMeses.getSelectedItem().toString().equals("August")){
                 
                 while(i < 31){
                     
                     cboDias.addItem(Integer.toString(dia));
                     i++;
                     dia++;
                     
                 }
                 
             }else if(cboMeses.getSelectedItem().toString().equals("September")){
                 
                 while(i < 30){
                     
                     cboDias.addItem(Integer.toString(dia));
                     i++;
                     dia++;
                     
                 }
                 
             }else if(cboMeses.getSelectedItem().toString().equals("October")){
                 
                 while(i < 31){
                     
                     cboDias.addItem(Integer.toString(dia));
                     i++;
                     dia++;
                     
                 }
                 
             }else if(cboMeses.getSelectedItem().toString().equals("November")){
                 
                 while(i < 30){
                     
                     cboDias.addItem(Integer.toString(dia));
                     i++;
                     dia++;
                     
                 }
                 
             }else if(cboMeses.getSelectedItem().toString().equals("December")){
                 
                 while(i < 31){
                     
                     cboDias.addItem(Integer.toString(dia));
                     i++;
                     dia++;
                     
                 }
                 
             }
                
            
        }catch(Exception ex){
            
            System.err.println("Ocurrio un error: " + ex.getMessage());
            
        }
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuardarOrden.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuardarOrden.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuardarOrden.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuardarOrden.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GuardarOrden dialog = new GuardarOrden(new javax.swing.JFrame(), true, 0);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarArticulo;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> cboAnios;
    private javax.swing.JComboBox<String> cboDias;
    private javax.swing.JComboBox<String> cboMeses;
    private javax.swing.JComboBox<Proveedor> cboProveedores;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblArticulos;
    private javax.swing.JTextField txtCliente;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtFolio;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
